language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script: python -m pytest . --cov=starter --cov-report term --cov-report xml
after_success:
  - codecov