site_name: Python-Starter
repo_url: https://github.com/SyntaxRules/python-starter/
theme: readthedocs
pages:
    - 'Overview': 'index.md'
    - 'User Guide':
        - 'Quick Start': 'quick-start.md'
        - 'Installation Instructions': 'installation-instructions.md'
    - 'License': 'license.md'