site_name: Python-Starter
repo_url: https://github.com/SyntaxRules/python-starter/
theme: readthedocs
docs_dir: 'starter'
pages:
    - 'Overview': 'index.md'
    - 'User Guide':
        - 'Quick Start': 'docs/quick-start.md'
        - 'Installation Instructions': 'docs/installation-instructions.md'
    - 'License': 'docs/license.md'